version = 0.1

[default.deploy.parameters]
stack_name = "venuu-backend-dev"
resolve_s3 = true
s3_prefix = "venuu-backend-dev"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoUserPoolArn=\"arn:aws:cognito-idp:ca-central-1:274828214214:userpool/ca-central-1_QS69ElCwX\" Stage=\"dev\""
image_repositories = []

[default.global.parameters]
region = "ca-central-1"
